### ISSUE TITLE
NPE in job_of

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold-ruby-sdk#9]
```
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/yegor/.rvm/gems/ruby-2.6.0/gems/zold-ruby-sdk-0.2.1/lib/zold/wts.rb:213:in `job_of'
    /Users/yegor/.rvm/gems/ruby-2.6.0/gems/zold-ruby-sdk-0.2.1/lib/zold/wts.rb:85:in `pull'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-ruby-sdk#9` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
